name: ci-cd



on:

  push:

    branches:

      - master

  pull_request:

    branches:

      - master



jobs:

  unit-tests:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

        with:

          node-version: "14.x"

      - run: npm ci

      - run: npm run build --if-present

      #- run: npm testss



  firebase-deploy:

    runs-on: ubuntu-latest

    needs: [unit-tests]

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

        with:

          node-version: "14.x"

      - run: npm ci

      - run: npm run build

      - uses: w9jds/firebase-action@master

        with:

          args: deploy --only hosting

        env:

          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}